### ISSUE TITLE
Mistake in Nordic tournament semifinals' singlet color

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#22] opened 2021-04-05 03:08 UTC
**Which application you are experiencing a problem with**
Arena 1.5.72.1

**Describe the bug**
In the Nordic tournament's semifinals there is a mistake in singlet color: as a rule, the wrestlers from group A wear red, from the group B - blue. Arena does it vice versa.

**To Reproduce**
1. Create Nordic tournament with 6 or 7 people
2. Check the singlet color Arena offers for semifinalists.

**Expected behavior**
In Nordic tournamet wrestlers in semifinals wear the following singlets: wrestlers from group A wear red singlets, wrestlers from group B - blue singlets

**Screenshots**
These are from test event and created intentionally for this bug report
[nordic_mistake.pdf](https://github.com/unitedworldwrestling/arena-public/files/6256076/nordic_mistake.pdf)
[nordic_mistake2.pdf](https://github.com/unitedworldwrestling/arena-public/files/6256077/nordic_mistake2.pdf)

**Comment by csabavirag** [comment] 2021-04-06 08:01
The way how the colours are assigned to wrestlers in Arena is not about their source group, but their ranking position within their group. 1st gets  Red, while 2nd is Blue.

Red: group **A 1st** vs. Blue: group B 2nd 
Red: group **B 1st** vs. Blue: group A 2nd

Checking internally if this must be done differently.

**Comment by theswix** [comment] 2021-04-07 02:44
Hello, @csabavirag. Thank you for swift reply. 

Well... I talked with a few IS referees from different countries yesterday, everyone confirmed that it is supposed to be blue and they are aware of this Arena behavior. Yet they believe it needs to be fixed. Actually I've had a conversation with @bouaziz1991 at one of the recent "Grand-Prix Ivan Yaryguin" tournaments in Krasnoyarsk, Russia and he admitted that he also knows about this bug. 

And last but not least. UWW rules (February 2021 ed.), Article 8 on page 12 states pretty much clear: 

"The semi-final matches will consist with:
- the first ranked in the group A against the second ranked in the group B
- the second ranked in the group A against the first ranked in the group B"

which by default leads us to the red singlets for wrestlers in group A and blue singlets for wrestlers in group B, since the first named and called to the mat wrestler is always in red.

Sorry for being so obnoxious, I used to be Q&A lead in one of the Russian Linux distribution company :)

**Comment by csabavirag** [comment] 2021-04-07 06:53
Hello @theswix, no problem at all. Let's wait for the official answer from the sports dept. Their words will confirm if this is by design or a bug and we will proceed accordingly. So thanks for raising this concern!

**Comment by csabavirag** [comment] 2021-04-14 11:19
Hello @theswix, the decision is to keep everything as is for now. At the next update of the rules book (most likely for the next Olympic season), we should expect clarification, but until that Arena remains and the top ranked wrestlers of their round robin group will get the "red singlet" associated.

Thanks for your understanding and patience.

**Closed by csabavirag** 2021-04-14 11:19 UTC
Labels: wontfix
